export const OBD_CODE_DEFINITIONS: Record<string, string> = {
  // P-Codes: Powertrain
  'P0100': 'Mass or Volume Air Flow Circuit Malfunction',
  'P0101': 'Mass Air Flow (MAF) Circuit Range/Performance Problem',
  'P0102': 'Mass or Volume Air Flow Circuit Low Input',
  'P0103': 'Mass or Volume Air Flow Circuit High Input',
  'P0104': 'Mass or Volume Air Flow Circuit Intermittent',
  'P0105': 'Manifold Absolute Pressure/Barometric Pressure Circuit Malfunction',
  'P0106': 'Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance Problem',
  'P0107': 'Manifold Absolute Pressure/Barometric Pressure Circuit Low Input',
  'P0108': 'Manifold Absolute Pressure/Barometric Pressure Circuit High Input',
  'P0109': 'Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent',
  'P0110': 'Intake Air Temperature Circuit Malfunction',
  'P0111': 'Intake Air Temperature Circuit Range/Performance Problem',
  'P0112': 'Intake Air Temperature Circuit Low Input',
  'P0113': 'Intake Air Temperature (IAT) Sensor 1 Circuit High Input',
  'P0115': 'Engine Coolant Temperature Circuit Malfunction',
  'P0116': 'Engine Coolant Temperature Circuit Range/Performance Problem',
  'P0117': 'Engine Coolant Temperature Circuit Low Input',
  'P0118': 'Engine Coolant Temperature Circuit High Input',
  'P0120': 'Throttle/Pedal Position Sensor/Switch A Circuit Malfunction',
  'P0121': 'Throttle/Pedal Position Sensor/Switch A Circuit Range/Performance Problem',
  'P0122': 'Throttle Position Sensor (TPS) Circuit Low Input',
  'P0123': 'Throttle/Pedal Position Sensor/Switch A Circuit High Input',
  'P0125': 'Insufficient Coolant Temperature for Closed Loop Fuel Control',
  'P0128': 'Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)',
  'P0130': 'O2 Sensor Circuit Malfunction (Bank 1 Sensor 1)',
  'P0131': 'O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)',
  'P0132': 'O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)',
  'P0133': 'O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)',
  'P0134': 'O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 1)',
  'P0135': 'O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)',
  'P0136': 'O2 Sensor Circuit Malfunction (Bank 1 Sensor 2)',
  'P0137': 'O2 Sensor Circuit Low Voltage (Bank 1 Sensor 2)',
  'P0138': 'O2 Sensor Circuit High Voltage (Bank 1 Sensor 2)',
  'P0139': 'O2 Sensor Circuit Slow Response (Bank 1 Sensor 2)',
  'P0140': 'O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 2)',
  'P0141': 'O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 2)',
  'P0171': 'System Too Lean (Bank 1)',
  'P0172': 'System Too Rich (Bank 1)',
  'P0173': 'Fuel Trim Malfunction (Bank 2)',
  'P0174': 'System Too Lean (Bank 2)',
  'P0175': 'System Too Rich (Bank 2)',
  'P0200': 'Injector Circuit Malfunction',
  'P0201': 'Injector Circuit Malfunction - Cylinder 1',
  'P0202': 'Injector Circuit Malfunction - Cylinder 2',
  'P0203': 'Injector Circuit Malfunction - Cylinder 3',
  'P0204': 'Injector Circuit Malfunction - Cylinder 4',
  'P0217': 'Engine Overtemp Condition',
  'P0219': 'Engine Overspeed Condition',
  'P0230': 'Fuel Pump Primary Circuit Malfunction',
  'P0231': 'Fuel Pump Secondary Circuit Low',
  'P0234': 'Engine Overboost Condition',
  'P0299': 'Turbocharger/Supercharger Underboost',
  'P0300': 'Random or Multiple Cylinder Misfire Detected',
  'P0301': 'Cylinder 1 Misfire Detected',
  'P0302': 'Cylinder 2 Misfire Detected',
  'P0303': 'Cylinder 3 Misfire Detected',
  'P0304': 'Cylinder 4 Misfire Detected',
  'P0305': 'Cylinder 5 Misfire Detected',
  'P0306': 'Cylinder 6 Misfire Detected',
  'P0307': 'Cylinder 7 Misfire Detected',
  'P0308': 'Cylinder 8 Misfire Detected',
  'P0320': 'Ignition/Distributor Engine Speed Input Circuit Malfunction',
  'P0321': 'Ignition/Distributor Engine Speed Input Circuit Range/Performance',
  'P0322': 'Ignition/Distributor Engine Speed Input Circuit No Signal',
  'P0325': 'Knock Sensor 1 Circuit Malfunction (Bank 1 or Single Sensor)',
  'P0330': 'Knock Sensor 2 Circuit Malfunction (Bank 2)',
  'P0335': 'Crankshaft Position Sensor A Circuit Malfunction',
  'P0336': 'Crankshaft Position Sensor A Circuit Range/Performance',
  'P0340': 'Camshaft Position Sensor Circuit Malfunction',
  'P0341': 'Camshaft Position Sensor Circuit Range/Performance',
  'P0350': 'Ignition Coil Primary/Secondary Circuit Malfunction',
  'P0351': 'Ignition Coil A Primary/Secondary Circuit Malfunction',
  'P0400': 'Exhaust Gas Recirculation Flow Malfunction',
  'P0401': 'Exhaust Gas Recirculation Flow Insufficient Detected',
  'P0402': 'Exhaust Gas Recirculation Flow Excessive Detected',
  'P0410': 'Secondary Air Injection System Malfunction',
  'P0411': 'Secondary Air Injection System Incorrect Flow Detected',
  'P0420': 'Catalyst System Efficiency Below Threshold (Bank 1)',
  'P0421': 'Warm Up Catalyst Efficiency Below Threshold (Bank 1)',
  'P0430': 'Catalyst System Efficiency Below Threshold (Bank 2)',
  'P0440': 'Evaporative Emission Control System Malfunction',
  'P0441': 'Evaporative Emission Control System Incorrect Purge Flow',
  'P0442': 'Evaporative Emission (EVAP) System Leak Detected (Small Leak)',
  'P0443': 'Evaporative Emission Control System Purge Control Valve Circuit Malfunction',
  'P0446': 'Evaporative Emission Control System Vent Control Circuit Malfunction',
  'P0455': 'Evaporative Emission Control System Leak Detected (Gross Leak)',
  'P0460': 'Fuel Level Sensor Circuit Malfunction',
  'P0500': 'Vehicle Speed Sensor (VSS) Malfunction',
  'P0501': 'Vehicle Speed Sensor Range/Performance',
  'P0502': 'Vehicle Speed Sensor Low Input',
  'P0503': 'Vehicle Speed Sensor Intermittent/Erratic/High',
  'P0505': 'Idle Control System Malfunction',
  'P0506': 'Idle Control System RPM Lower Than Expected',
  'P0507': 'Idle Control System RPM Higher Than Expected',
  'P0510': 'Closed Throttle Position Switch Malfunction',
  'P0551': 'Power Steering Pressure Sensor Circuit Range/Performance',
  'P0560': 'System Voltage Malfunction',
  'P0561': 'System Voltage Unstable',
  'P0562': 'System Voltage Low',
  'P0563': 'System Voltage High',
  'P0600': 'Serial Communication Link Malfunction',
  'P0601': 'Internal Control Module Memory Check Sum Error',
  'P0602': 'Control Module Programming Error',
  'P0603': 'Internal Control Module Keep Alive Memory (KAM) Error',
  'P0604': 'Internal Control Module Random Access Memory (RAM) Error',
  'P0605': 'Internal Control Module Read Only Memory (ROM) Error',
  'P0606': 'ECM/PCM Processor Fault',
  'P0700': 'Transmission Control System Malfunction',
  'P0701': 'Transmission Control System Range/Performance',
  'P0702': 'Transmission Control System Electrical',
  'P0703': 'Torque Converter/Brake Switch B Circuit Malfunction',
  'P0704': 'Clutch Switch Input Circuit Malfunction',
  'P0705': 'Transmission Range Sensor Circuit Malfunction (PRNDL Input)',
  'P0706': 'Transmission Range Sensor Circuit Range/Performance',
  'P0710': 'Transmission Fluid Temperature Sensor Circuit Malfunction',
  'P0715': 'Input/Turbine Speed Sensor Circuit Malfunction',
  'P0720': 'Output Speed Sensor Circuit Malfunction',
  'P0730': 'Incorrect Gear Ratio',
  'P0731': 'Gear 1 Incorrect Ratio',
  'P0732': 'Gear 2 Incorrect Ratio',
  'P0733': 'Gear 3 Incorrect Ratio',
  'P0734': 'Gear 4 Incorrect Ratio',
  'P0735': 'Gear 5 Incorrect Ratio',
  'P0740': 'Torque Converter Clutch Circuit Malfunction',
  'P0741': 'Torque Converter Clutch Circuit Performance or Stuck Off',
  'P0750': 'Shift Solenoid A Malfunction',
  'P0751': 'Shift Solenoid A Performance or Stuck Off',
  'P0753': 'Shift Solenoid A Electrical',
  'P0755': 'Shift Solenoid B Malfunction',
  'P0756': 'Shift Solenoid B Performance or Stuck Off',
  'P0758': 'Shift Solenoid B Electrical',
  'P0801': 'Reverse Inhibit Control Circuit Malfunction',
  'P0803': '1-4 Upshift (Skip Shift) Solenoid Control Circuit Malfunction',
  'P0804': '1-4 Upshift (Skip Shift) Lamp Control Circuit Malfunction',

  // C-Codes: Chassis
  'C0035': 'Left Front Wheel Speed Sensor Circuit Malfunction',
  'C0040': 'Right Front Wheel Speed Sensor Circuit Malfunction',
  'C0045': 'Left Rear Wheel Speed Sensor Circuit Malfunction',
  'C0050': 'Right Rear Wheel Speed Sensor Circuit Malfunction',
  'C0221': 'Right Front Wheel Speed Sensor Circuit Open',
  'C0222': 'Right Front Wheel Speed Sensor Signal Missing',
  'C0223': 'Right Front Wheel Speed Sensor Signal Erratic',
  'C0225': 'Left Front Wheel Speed Sensor Circuit Open',
  'C0226': 'Left Front Wheel Speed Sensor Signal Missing',
  'C0227': 'Left Front Wheel Speed Sensor Signal Erratic',

  // B-Codes: Body
  'B0001': 'Driver Airbag Deployment Control - Stage 1',
  'B0002': 'Driver Airbag Deployment Control - Stage 2',
  'B0003': 'Driver Airbag Deployment Control - Stage 3',
  'B0010': 'Passenger Airbag Deployment Control - Stage 1',
  'B0011': 'Passenger Airbag Deployment Control - Stage 2',
  'B0012': 'Passenger Airbag Deployment Control - Stage 3',
  'B1201': 'Fuel Sender Circuit Failure',
  'B1202': 'Fuel Sender Circuit Open',
  'B1203': 'Fuel Sender Circuit Short to Battery',
  'B1204': 'Fuel Sender Circuit Short to Ground',

  // U-Codes: Network
  'U0001': 'High Speed CAN Communication Bus',
  'U0002': 'High Speed CAN Communication Bus Performance',
  'U0003': 'High Speed CAN Communication Bus (+)',
  'U0004': 'High Speed CAN Communication Bus (+)',
  'U0005': 'High Speed CAN Communication Bus (-)',
  'U0100': 'Lost Communication With ECM/PCM',
  'U0101': 'Lost Communication With TCM',
  'U0121': 'Lost Communication With Anti-Lock Brake System (ABS) Control Module',
  'U0155': 'Lost Communication With Instrument Panel Cluster (IPC) Control Module',
  'U0401': 'Invalid Data Received From ECM/PCM',
};
